/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.GuessGame;
import Classes.Gui;
import javax.swing.JOptionPane;

/**
 *
 * @author mohamed
 */
public class NumberingGame extends javax.swing.JFrame {

    /**
     * Creates new form NumberingGame
     */
    public NumberingGame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelreset = new javax.swing.JLabel();
        labelbestscore = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelpicturegame = new javax.swing.JLabel();
        labeltext = new javax.swing.JLabel();
        fieldguess = new javax.swing.JTextField();
        btnguess = new javax.swing.JButton();
        labelattempts = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Number Guess CodSoft");
        setResizable(false);

        labelreset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/icons8-reset-64.png"))); // NOI18N
        labelreset.setToolTipText("Reset");

        labelbestscore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelbestscore.setText("your score");
        labelbestscore.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Number Game");

        labelpicturegame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelpicturegame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/logo (1).png"))); // NOI18N

        labeltext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labeltext.setText("Enter number from (1-100)");

        fieldguess.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fieldguess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldguessActionPerformed(evt);
            }
        });

        btnguess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/question-mark (2).png"))); // NOI18N
        btnguess.setText("Guess");
        btnguess.setToolTipText("Your Guess");
        btnguess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguessActionPerformed(evt);
            }
        });

        labelattempts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelattempts.setText("Attempts: 10");
        labelattempts.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelreset, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(119, 119, 119)
                                .addComponent(labelbestscore, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelpicturegame, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(fieldguess, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labeltext)
                                        .addGap(146, 146, 146))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelattempts, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                                .addComponent(btnguess, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelbestscore, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelreset, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelpicturegame, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labeltext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldguess, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnguess, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelattempts, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(59, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldguessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldguessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldguessActionPerformed

    private void btnguessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguessActionPerformed
        guess();
    }//GEN-LAST:event_btnguessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguess;
    private javax.swing.JTextField fieldguess;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelattempts;
    private javax.swing.JLabel labelbestscore;
    private javax.swing.JLabel labelpicturegame;
    private javax.swing.JLabel labelreset;
    private javax.swing.JLabel labeltext;
    // End of variables declaration//GEN-END:variables
    
    Gui gui;
    private int yourscore,randomnumber;
    private int attempts=10;
    private void init(){
        gui = new Gui();
        gui.centerframe(this);
        gui.setIcon(this);
        randomnumber = GuessGame.randomNumber();  
    }
    private void guess(){
        if(fieldguess.getText().isEmpty()){
            Gui.message("you did not enter value from 1 to 100", 0);
            fieldguess.requestFocus();
        }
        else if(Integer.parseInt(fieldguess.getText()) > 100||Integer.parseInt(fieldguess.getText()) < 1){
            Gui.message("enter number from 1 to 100", 0);
            fieldguess.requestFocus();
        }
        else{
            int userinput = Integer.parseInt(fieldguess.getText());
            if (userinput == randomnumber){
                Gui.message("You win!", 1);
            yourscore=yourscore+attempts;
            labelbestscore.setText("Your Score: "+yourscore);
            Object[] options ={"YES","NO"};
            int x = JOptionPane.showOptionDialog(this, "Do you want to play again Yes/No", "MESSAGE", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE, null,options,null);
            if(x == JOptionPane.YES_OPTION){
                newgame();
            }else{
                System.exit(0);
            }
            }
            else{
                if(userinput<randomnumber){
                    Gui.message(userinput+" is less than the number", 2);
                }
                else{
                    Gui.message(userinput+" is greater than the number", 2);
                }
                attempts--;
                labelattempts.setText("Attempts: "+attempts);
                if(attempts==0){
                    Gui.message("you used all the attempts hard luck :/", 0);
                    Object[] options ={"YES","NO"};
            int x = JOptionPane.showOptionDialog(this, "Do you want to play again Yes/No", "MESSAGE", JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE, null,options,null);
            if(x == JOptionPane.YES_OPTION){
                newgame();
            }else{
                System.exit(0);
            }
                }
            }
        }
        
    }
    private void newgame(){
            fieldguess.setText("");
            fieldguess.requestFocus();
            yourscore=0;
            labelattempts.setText("Attempts: 10");
            randomnumber = GuessGame.randomNumber();
            
    }
}
